name: Build
run-name: Build editor exe
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - run: dotnet restore
      - run: dotnet publish -c Release -r win-x64 --no-self-contained
      - uses: actions/download-artifact@v4
        with:
          name: Build
          path: viewBuild
          github-token: ${{ secrets.REPO_GH_TOKEN }}
          repository: LingFeng-bbben/MajdataView
      - run: ls -R
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: publish
